[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "salesforce.marketingcloud"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["marketing", "sales", "communication", "Vendor/Salesforce", "Area/Social Media Marketing", "Type/Connector"]
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-salesforce.marketingcloud"

[build-options]
observabilityIncluded = true
